import type { Feature, User, Comment } from './types'

export const mockUser: User = {
  id: 'user-1',
  name: 'Alex Climber',
  email: 'alex@climbing.app',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=alex',
  bio: 'Passionate climber exploring new routes across the country.',
  links: [
    { type: 'mountainProject', url: 'https://mountainproject.com/user/alex' },
    { type: 'youtube', url: 'https://youtube.com/@alexclimbs' },
  ],
  createdAt: '2024-01-15',
}

export const mockComments: Comment[] = [
  {
    id: 'c1',
    userId: 'user-2',
    userName: 'Sarah Boulder',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sarah',
    text: 'Great boulder! The north face has some amazing holds.',
    createdAt: '2025-01-10T14:30:00Z',
    likes: 5,
    likedByUser: false,
    replies: [
      {
        id: 'c1-r1',
        userId: 'user-3',
        userName: 'Mike Stone',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=mike',
        text: 'Agreed! The crimp at the top is solid.',
        createdAt: '2025-01-10T15:45:00Z',
        likes: 2,
        likedByUser: true,
        replies: [],
      },
    ],
  },
  {
    id: 'c2',
    userId: 'user-4',
    userName: 'Emma Rocks',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=emma',
    text: 'Watch out for the loose rock on the east side.',
    createdAt: '2025-01-08T09:15:00Z',
    likes: 12,
    likedByUser: false,
    replies: [],
  },
]

export const mockFeatures: Feature[] = [
  {
    id: 'B47784074N91685652W',
    type: 'boulder',
    name: 'Sunset Boulder',
    latitude: 47.78407,
    longitude: -91.68565,
    elevation: 474,
    height: 4.4,
    length: 6.8,
    width: 5.1,
    distanceToRoad: 0,
    bushwhackDistance: 0,
    hardness: 7,
    isFavorite: true,
    isSeen: true,
    seenByAnyone: true,
    notARock: null,
    modelUrl: undefined, // Was '/assets/3d/duck.glb' which caused 404
    climbs: [
      {
        id: 'climb-1',
        name: 'North Face Direct',
        rating: 'V5',
        ratingSystem: 'v-scale',
        stars: 4,
        status: 'send',
        userId: 'user-1',
        createdAt: '2025-01-05',
      },
      {
        id: 'climb-2',
        name: 'East Arete',
        rating: 'V3',
        ratingSystem: 'v-scale',
        stars: 3,
        status: 'project',
        userId: 'user-2',
        createdAt: '2025-01-08',
      },
    ],
    photos: [
      {
        id: 'photo-1',
        url: 'https://images.unsplash.com/photo-1522163182402-834f871fd851?w=800',
        thumbnailUrl: 'https://images.unsplash.com/photo-1522163182402-834f871fd851?w=200',
        userId: 'user-1',
        userName: 'Alex Climber',
        note: 'Amazing golden hour light',
        createdAt: '2025-01-05T17:30:00Z',
      },
      {
        id: 'photo-2',
        url: 'https://images.unsplash.com/photo-1507034589631-9433cc6bc453?w=800',
        thumbnailUrl: 'https://images.unsplash.com/photo-1507034589631-9433cc6bc453?w=200',
        userId: 'user-2',
        userName: 'Sarah Boulder',
        createdAt: '2025-01-06T10:00:00Z',
      },
    ],
    comments: mockComments,
    links: [
      { type: 'mountainProject', url: 'https://mountainproject.com/route/12345', label: 'Mountain Project' },
    ],
    isPublished: true,
    hasLocalEdits: false,
  },
  {
    id: 'B47785123N91684321W',
    type: 'boulder',
    name: 'Hidden Gem',
    latitude: 47.78512,
    longitude: -91.68432,
    elevation: 482,
    height: 3.2,
    length: 4.5,
    width: 3.8,
    distanceToRoad: 150,
    bushwhackDistance: 50,
    hardness: 5,
    isFavorite: false,
    isSeen: false,
    seenByAnyone: false,
    notARock: null,
    climbs: [],
    photos: [],
    comments: [],
    links: [],
    isPublished: false,
    hasLocalEdits: false,
  },
  {
    id: 'C47786789N91683456W',
    type: 'cliff',
    name: 'Eagle Wall',
    latitude: 47.78679,
    longitude: -91.68346,
    elevation: 520,
    height: 25,
    length: 45,
    width: 8,
    distanceToRoad: 300,
    bushwhackDistance: 100,
    hardness: 8,
    isFavorite: true,
    isSeen: true,
    seenByAnyone: true,
    notARock: null,
    climbs: [
      {
        id: 'climb-3',
        name: 'Classic Crack',
        rating: '5.10a',
        ratingSystem: 'yds',
        stars: 5,
        status: 'send',
        userId: 'user-1',
        createdAt: '2024-12-20',
      },
    ],
    photos: [
      {
        id: 'photo-3',
        url: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800',
        thumbnailUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=200',
        userId: 'user-3',
        userName: 'Mike Stone',
        note: 'The main wall from the approach trail',
        createdAt: '2024-12-18T14:00:00Z',
      },
    ],
    comments: [
      {
        id: 'c3',
        userId: 'user-5',
        userName: 'Jake Trad',
        userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=jake',
        text: 'Bring extra cams for the wide section!',
        createdAt: '2024-12-22T11:00:00Z',
        likes: 8,
        likedByUser: false,
        replies: [],
      },
    ],
    links: [],
    isPublished: true,
    hasLocalEdits: false,
  },
  {
    id: 'B47784500N91686000W',
    type: 'boulder',
    name: 'Tree Stump',
    latitude: 47.78450,
    longitude: -91.68600,
    elevation: 470,
    height: 2.5,
    length: 3.0,
    width: 2.8,
    distanceToRoad: 20,
    bushwhackDistance: 0,
    hardness: 0,
    isFavorite: false,
    isSeen: true,
    seenByAnyone: true,
    notARock: 'tree',
    climbs: [],
    photos: [],
    comments: [],
    links: [],
    isPublished: false,
    hasLocalEdits: false,
  },
]

export const publicLands = [
  {
    id: 'superior-nf',
    name: 'Superior National Forest',
    type: 'national-forest',
    bounds: [
      [-91.72, 47.75],
      [-91.72, 47.82],
      [-91.64, 47.82],
      [-91.64, 47.75],
    ],
  },
]

export const scannedAreas = [
  {
    id: 'scan-1',
    bounds: [
      [-91.70, 47.77],
      [-91.70, 47.80],
      [-91.66, 47.80],
      [-91.66, 47.77],
    ],
  },
]
